name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test

    - name: Send message to Telegram
      run: |
        curl -s -X POST https://api.telegram.org/bot7033492602:AAHBzDr35i9AZPjPGbDCuMJhPeeW91j9coA/sendMessage -d chat_id=-4246817754 -d text="ВСЁ ОК!"
